version: "3"

services:
  app:
    build: .
    environment:
      AWS_REGION: $AWS_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      APP_ID: $APP_ID
      ENV_ID: $ENV_ID
      CONFIG_ID: $CONFIG_ID
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "scripts/deploy-prod.sh"
