version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: ["./run-debug.sh"]
