name: Continuous Integration

on:
  push:
    branches: [ '**' ]
    paths-ignore: [ 'terraform/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'src/go.mod'
          cache-dependency-path: |
            src/go.sum
            cdk/go.sum

      - name: Unit tests
        run: go test -C src -v

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: test
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - uses: aws-actions/configure-aws-credentials@v6
        id: configure-aws
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_CD_ROLE_ARN }}

      - name: Build
        run: CGO_ENABLED=0 go build -C src -tags lambda.norpc -ldflags="-s -w" -o bin/bootstrap main.go

      - name: Deploy
        env:
          AWS_ACCOUNT_ID: ${{ steps.configure-aws.outputs.aws-account-id }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          APP_ID: ${{ vars.APP_ID }}
          ENV_ID: ${{ vars.ENV_ID }}
          CONFIG_ID: ${{ vars.CONFIG_ID }}
          APP_ENV: "prod"
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: cd cdk && cdk deploy --require-approval never
