name: Continuous Integration

on:
  push:
    branches: [ '**' ]
    paths-ignore: [ 'terraform/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  SAM_CLI_TELEMETRY: "0" # disable AWS telemetry in the SAM CLI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'src/go.mod'

      - name: Unit tests
        run: go test -C src -v

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build
        run: CGO_ENABLED=0 go build -C src -tags lambda.norpc -ldflags="-s -w" -o bin/bootstrap main.go

      - name: Deploy
        env:
          APP_ID: ${{ vars.APP_ID }}
          ENV_ID: ${{ vars.ENV_ID }}
          CONFIG_ID: ${{ vars.CONFIG_ID }}
        run: cd cdk && cdk deploy --require-approval never
