name: Continuous Integration

on:
  push:
    branches: [ '**' ]
    paths-ignore: [ 'terraform/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  SAM_CLI_TELEMETRY: "0" # disable AWS telemetry in the SAM CLI

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'src/go.mod'
    - name: Unit tests
      run: go test -C src -v

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: test
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    - run: sam build --use-container
    - run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
        --parameter-overrides \
          ParameterKey=AppId,ParameterValue=${{ secrets.APP_ID }} \
          ParameterKey=EnvId,ParameterValue=${{ secrets.ENV_ID }} \
          ParameterKey=ConfigId,ParameterValue=${{ secrets.CONFIG_ID }}
